# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from google.colab import files

from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV

from yellowbrick.cluster import KElbowVisualizer

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
df = pd.read_csv("/content/data_clustering_inverse.csv")
df.rename(columns={'Cluster': 'Target'}, inplace=True)

In [3]:
df.head()

TransactionAmount  PreviousTransactionDate  TransactionType  Location  \
0           0.003367                1689800.0                1    1290.0   
1           0.091548                2927330.0                1     301.0   
2           0.030687                3136070.0                1     688.0   
3           0.044861                2032730.0                1    1161.0   
4           0.022374                1577975.0                1     903.0   

   Channel  CustomerAge  CustomerOccupation  TransactionDuration  \
0      0.0     0.838710                 0.0             0.244828   
1      0.0     0.806452                 0.0             0.451724   
2      6.0     0.016129                12.0             0.158621   
3      6.0     0.129032                12.0             0.051724   
4      0.0     0.000000                12.0             0.558621   

   LoginAttempts  AccountBalance  TransactionDate  CustomerAge_Bin  \
0            0.0        0.336832          37800.0     (0.645, 1.0]   
1            0.0        0.918055          69120.0     (0.645, 1.0]   
2            0.0        0.068637          14760.0  (-0.001, 0.145]   
3            0.0        0.569198          58680.0  (-0.001, 0.145]   
4            0.0        0.045738           4680.0  (-0.001, 0.145]   

   CustomerAge_Bin_Encoded  Target  
0                      9.0       1  
1                      9.0       1  
2                      0.0       0  
3                      0.0       0  
4                      0.0       0

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [4]:
X = df.drop('Target', axis=1)
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 13), (346, 13), (1382,), (346,))

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [5]:
model_dt = DecisionTreeClassifier(random_state=42)
# Drop the 'CustomerAge_Bin' column as it contains string values not suitable for the model
X_train = X_train.drop('CustomerAge_Bin', axis=1)
X_test = X_test.drop('CustomerAge_Bin', axis=1)
model_dt.fit(X_train, y_train)
y_pred = model_dt.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9942196531791907
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        93
           1       0.99      0.99      0.99       145
           2       0.99      0.99      0.99       108

    accuracy                           0.99       346
   macro avg       0.99      0.99      0.99       346
weighted avg       0.99      0.99      0.99       346

Confusion Matrix:
[[ 93   0   0]
 [  0 144   1]
 [  0   1 107]]


In [6]:
joblib.dump(model_dt, 'decision_tree_model.h5')
files.download('decision_tree_model.h5')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [7]:
model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
accuracy_rf

0.9942196531791907

In [8]:
results = []

models = {
    "Decision Tree": model_dt,
    "Random Forest": model_rf,
}

for name, model in models.items():
    y_pred = model.predict(X_test)
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, average='weighted'),
        "Recall": recall_score(y_test, y_pred, average='weighted'),
        "F1-Score": f1_score(y_test, y_pred, average='weighted')
    })

df_results = pd.DataFrame(results)
df_results

Model  Accuracy  Precision   Recall  F1-Score
0  Decision Tree   0.99422   0.994220  0.99422  0.994220
1  Random Forest   0.99422   0.994239  0.99422  0.994217

In [9]:
joblib.dump(model_rf, 'explore_random_forest_classification.h5')
files.download('explore_random_forest_classification.h5')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [10]:
best_model = GridSearchCV(RandomForestClassifier(random_state=42),
                          {'n_estimators':[50,100,200],
                           'max_depth':[None,5,10],
                           'min_samples_split':[2,5,10],
                           'min_samples_leaf':[1,2,4]},
                          cv=5, scoring='accuracy', n_jobs=-1).fit(X_train, y_train).best_estimator_

accuracy = accuracy_score(y_test, best_model.predict(X_test))
accuracy

0.9884393063583815

In [11]:
y_pred = best_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

accuracy, precision, recall, f1

(0.9884393063583815,
 0.9885969521807673,
 0.9884393063583815,
 0.9884609221347856)

In [12]:
joblib.dump(best_model, 'tuning_classification.h5')
files.download('tuning_classification.h5')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

End of Code